Mvc4-SportsStore/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Entities;

namespace SportsStore.Controllers
{
    public class AdminController : Controller
    {
        private IProductRepository repository;


        public AdminController(IProductRepository repo)
        {
            repository = repo;
        }

       [Authorize]
        public ActionResult Index()
        {

            return View(repository.Products);
        }

        public ViewResult Edit(int productID) {

            Product product = repository.Products
                              .FirstOrDefault(p => p.ProductID == productID);
            return View(product);           
        }

       
        public ViewResult Create()
        {
            return View("Edit", new Product());
        }

        [HttpPost]
        public ActionResult Delete(int productId)
        {
            
            Product deletedProduct = repository.DeleteProduct(productId);
            if (deletedProduct != null) {
                TempData["message"] = string.Format("{0} was deleted",
                                        deletedProduct.Name);
            }

            return RedirectToAction("Index");
            
        }

        [HttpPost]
        public ActionResult Edit(Product product, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    product.ImageMimeType = image.ContentType;
                    product.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(product.ImageData, 0, image.ContentLength);
                }
                repository.SaveProduct(product);
                TempData["message"] = string.Format("{0} has been saved", product.Name);
                return RedirectToAction("Index");
            }
            else
            {
                // there is something wrong with the data values
                return View(product);
            }
        }

    }
}

Mvc4-SportsStore/Views/Admin/Edit.cshtml
@model SportsStore.Domain.Entities.Product
@{
    ViewBag.Title = "Admin: Edit " + @Model.Name;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Edit @Model.Name</h1>
    @using (Html.BeginForm("Edit", "Admin",
    FormMethod.Post, new { enctype = "multipart/form-data" })) {
    @Html.EditorForModel()
    <div class="editor-label">Image</div>
    <div class="editor-field">
    @if (Model.ImageData == null) {
    @:None
    } else {
        <img width="150" height="150"
        src="@Url.Action("GetImage", "Product", new { Model.ProductID })" />
        }
        <div>Upload new image: <input type="file" name="Image" /></div>
        </div>
        <input type="submit" value="Save" />
        @Html.ActionLink("Cancel and return to List", "Index")
        }   

Mvc4-SportsStore/Views/Admin/Index.cshtml
@model IEnumerable<SportsStore.Domain.Entities.Product>
@{
    ViewBag.Title = "Admin: All Products";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>All Products</h1>
<p style="float:right">
 @using (Html.BeginForm("Logout", "Account"))
 { 
    <p><input type="submit" value="Cerrar sesión" /></p>
 }

<table class="Grid">
    <tr>
    <th>ID</th>
    <th>Name</th>
    <th class="NumericCol">Price</th>
    <th>Actions</th>
    </tr>
    @foreach (var item in Model) {
    <tr>
    <td>@item.ProductID</td>
        
    <td>@Html.ActionLink(item.Name, "Edit", new { item.ProductID })</td>
    <td class="NumericCol">@item.Price.ToString("c")</td>
    <td>
        @using (Html.BeginForm("Delete", "Admin")) {
        @Html.Hidden("ProductID", item.ProductID)
        <input type="submit" value="Delete"/>        
        }
    </td>
    </tr>
    }
</table>

<p>@Html.ActionLink("Add a new product", "Create")</p>
<p style="float:left;color:Red">@Html.ActionLink("Volver a la tienda","list","Product")</p>